### ISSUE TITLE
Login security

### ISSUE THREAD

**Issue by ldd** [amedeedaboville/battleships#2]
Some parts of login should be done in /server/

This is very non-critical but I'll put it here so that we don't forget.

**Comment by ldd** [comment]
We forgot ;_;
:D

**Comment by johnsaigle** [comment]
It was a noble effort

**Comment by amedeedaboville** [comment]
We were the only ones who didn't crash, it's a win in my book
#priorities

**Comment by charleshwright** [comment]
Nice to know you guys are still around on github!

**Comment by ldd** [comment]
<3
